### ISSUE TITLE
executeQueryPromise extension

### ISSUE THREAD

**Issue by mgordic** [koltyakov/sp-jsom-node#10]
Hi Andrew,

Is it possible to use your extension executeQueryPromise in regular typescript project? 

I am interested to use it in my data access layer written in typescript and JSOM, but I can't manage it to work.

Is there a way to define extension for it in typecript?

Thank you
Marko

**Comment by koltyakov** [comment]
Hi @mgordic, 

What do you mean by regular TS projects? None Node.js but in browser code, maybe?
Anyways, it's possible. The [helper](https://github.com/koltyakov/sp-jsom-node/blob/master/src/extensions/executeQueryPromise.ts), it's [definition](https://github.com/koltyakov/sp-jsom-node/blob/master/src/extensions/definitions.ts) and [initialization](https://github.com/koltyakov/sp-jsom-node/blob/master/src/JsomNode.ts#L222) should be copied to the project, initialization of the helper should be called after JSOM is loaded.

**Comment by mgordic** [comment]
Hi @koltyakov ,

Thank you for quick reply.

Let me explain you my scenario:

I am having an Angular 7 app and there I have my data access layer that is using JSOM to get data from SharePoint site.

So what I want is to somehow use your SP.ClientContext extension, and then to use async/await to make my code cleaner and easier to maintain.

**Comment by koltyakov** [comment]
What I assumed and described is exactly what you need.

Please try something like:

```typescript
declare window {
  namespace SP {
    interface ClientRuntimeContext {
      executeQueryPromise (): Promise<void>;
    }
  }
}

const executeQueryPromise = (clientContext: SP.ClientRuntimeContext): Promise<void> => {
  return new Promise((resolve, reject) => {
    clientContext
      .executeQueryAsync(
        resolve,
        (...args) => reject(args[1].get_message())
      );
  });
};

SP.SOD.executeOrDelayUntilScriptLoaded(() => {

    (SP as any).ClientRuntimeContext.prototype.executeQueryPromise = function (): Promise<void> {
        return executeQueryPromise(this);
    };

    const ctx = SP.ClientContext.get_current();

    console.log(ctx.hasOwnProperty('executeQueryPromise'));

}, 'sp.js');
```

At the moment can't verify if it works, but the final solution should be very close to the sample above.

**Comment by mgordic** [comment]
Super, I will give it a try. I was missing how prototype was defined in your code... Thank you!!
