### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by georgyevv** [koltyakov/sp-jsom-node#2]
Hello, 

Can i use this library in Angular 5 application. I am trying but nothing so far.

Thank you in advance!
Best Regards,
Jordan

**Comment by koltyakov** [comment]
The library is for "server-side" usage in Node.js process, not for the browser. In a browser, JSOM works right out of the box with the standard SharePoint script on demand functionality.

I'm wondering what's your scenario? Maybe you were thinking about local dev server with a possibility of communicating with SharePoint API? In such a scenario [sp-rest-proxy](https://github.com/koltyakov/sp-rest-proxy) might be helpful. Here is the [example](http://johnliu.net/blog/2017/9/angular-4-sharepoint-on-premises-localhost-development-and-sp-rest-proxy) how folks use it in Angular.

**Comment by georgyevv** [comment]
Well here is what I want to do. I am creating SharePoint hosted add-in. And in order to develop it I always need to deploy the application or only the angular build files to some document library in order to see the result and test the quieries. I found library that using gulp I can do the following. Write: ng build -watch, start the gulp task and now the files are automatically uploaded to the SharePoint library on every file save. But I think it will boost the development time even further if I can develop locally and deploy only once when everything is ready. That's why I hoped I can somehow hack it with your library. I hope it makes sense now.

**Comment by koltyakov** [comment]
Gotcha! So it’s the scenario I’ve described with sp-rest-proxy, wich perfectly fits the task. 
Are you using JSOM for communication with the API? With JSOM its javascripts and some global variables and shims should be hacked into localy served page. On the other hand, REST doesn’t require any tweaks. You can just send cors requests to stand alone hosted proxy, or configure webpack dev server to proxy api call to sp-rest-proxy. Second option is cooler as senging to http://localhost:8000/_api/... (where localhost:8000 is your local dev server with angular app hot reloading, in-memory compilation, etc.) authorized requests are sent to SharePoint as if it were a local API.
