### ISSUE TITLE
Request Error connect ETIMEDOUT

### ISSUE THREAD

**Issue by guruparan** [koltyakov/sp-jsom-node#3]
Hi 
I'm getting a ETIMEDOUT error while accessing multiple groups. is there any way to increase the time out.
I'm using javascript.
tried set_requestTimeout in the context bu no use.

**Comment by koltyakov** [comment]
Hi @guruparan,

Thanks for posting the issue. 
I’ll take a look into this. 

Are you experience such behavior all the way or time to time? 
What do you mean by “accessing multiple groups”? Can it be that the JSOM instructions XML package is too large (to many actions batched in one executeQueryAsync)?

Will the same request fail in a context of SharePoint page?

**Comment by guruparan** [comment]
i'm trying to get all the groups in a site along with the members, but first i get the groups which is ok but when i have a loop to send async requests for each group to get the members then it fails in the middle tried from a different network as well still no use.

**Comment by koltyakov** [comment]
Out of curiosity, will the [following approach](https://github.com/koltyakov/sp-jsom-node/blob/master/test/manual/groups.ts) work for you? It get's groups and users in one call.

For the async queue, I would recommend sending the requests in a sequence using "for of" loop and await inside. 

Also, I can't reproduce. So will dig with a timeout stuff later on more deeply.

**Comment by guruparan** [comment]
Hi Thanks for the reply
Is there a javascript version of this ?

**Comment by koltyakov** [comment]
JS version is almost identical none of TypeScript deep specifics is used in the example.

JS's might look like:

```javascript
// jsom node initiation is ommited

const clientContext = SP.ClientContext.get_current();
let oWeb = clientContext.get_web();
let oGroups = oWeb.get_siteGroups();

clientContext.load(oGroups, 'Include(Id,Title,Users)');

clientContext.executeQueryAsync(_ => {

  let users = oGroups.get_data().map(group => {
    return {
      group: group.get_title(),
      users: group.get_users().get_data().map(user => {
        return {
          id: user.get_id(),
          title: user.get_title()
        };
      })
    };
  });

  console.log(users);

}, (_, args) => {
  console.log(args.get_message())
});
```

**Comment by guruparan** [comment]
Thanks for the reply, i'll try this out.
