### ISSUE TITLE
using sp-jsom-node in an azure function to update regional settings of a sharepoint site

### ISSUE THREAD

**Issue by karthikramasubramanian** [koltyakov/sp-jsom-node#30]
Hi Andrew,
I am trying to write a TypeScript azure function that can update the regional settings of a sharepoint site.   Initially I tried using csom-node without much success and after some search found sp-jsom-node.  I am happy to say that I am able to authenticate and connect to the site and retrieve the regional settings.  But when I tried to add the code to update the regional settings I came to realise that there are no set methods or update method in the regionalsettings object.  I wanted to check with you if this is a limitation by design?
I looked into the node_modules>@types>sharepoint>index.d.ts>SP>RegionalSettings.. i have copied the extract for your reference.  As you can see there is not set or update methods.  Is there something else i need to do to be able to update regional settings?
   class RegionalSettings extends SP.ClientObject {
        get_adjustHijriDays(): number;
        get_alternateCalendarType(): number;
        get_aM(): string;
        get_calendarType(): number;
        get_collation(): number;
        get_collationLCID(): number;
        get_dateFormat(): number;
        get_dateSeparator(): string;
        get_decimalSeparator(): string;
        get_digitGrouping(): string;
        get_firstDayOfWeek(): number;
        get_firstWeekOfYear(): number;
        get_isEastAsia(): boolean;
        get_isRightToLeft(): boolean;
        get_isUIRightToLeft(): boolean;
        get_listSeparator(): string;
        get_localeId(): number;
        get_negativeSign(): string;
        get_negNumberMode(): number;
        get_pM(): string;
        get_positiveSign(): string;
        get_showWeeks(): boolean;
        get_thousandSeparator(): string;
        get_time24(): boolean;
        get_timeMarkerPosition(): number;
        get_timeSeparator(): string;
        get_timeZone(): SP.TimeZone;
        get_timeZones(): SP.TimeZoneCollection;
        get_workDayEndHour(): number;
        get_workDays(): number;
        get_workDayStartHour(): number;
    }

**Comment by koltyakov** [comment]
Hi @karthikramasubramanian,

Thanks for trying the library.

To update regional settings this code snippet is applicable:

```typescript
const clientContext = SP.ClientContext.get_current();
const oWeb = clientContext.get_web();
const reginalSettings = oWeb.get_regionalSettings();

const untypedRS = reginalSettings as any; // `@types/sharepoint` has gaps

untypedRS.set_localeId(1033);
untypedRS.update();

await clientContext.executeQueryPromise();
```

The library uses `@types/sharepoint` for bringing types to JSOM code, unfortunately the coverage of the types is not complete, as they are manually crafted by some community folks who are not in the SP business anymore (at least community activities). For the most of the cases it's ok, but not for some edge cases. I don't think that the typings for JSOM will evolve as CSOM/JSOM is kind of a legacy APIs even while only these APIs provide features still absent in REST and especially in Graph API.

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov,

Thank you for your quick response.  Your suggestion, solved my issue and am happy to say that my azure function is working fine.  

Regards
Karthik

**Comment by koltyakov** [comment]
Great!

**Comment by karthikramasubramanian** [comment]
Hi Andre,
I guess, I was a bit premature in claiming it worked.  It does work in two scenarios:
1. when I am debugging my azure function locally in VS Code http://localhost:7071....
2. When i deploy the function to azure and am testing it from the azure portal

It does not work when I try to consume the azure function from within an spfx webpart (other functions in the deployment work though).  It also doesnt work when I try and test it from Postman.
The appId and appSecret for connecting to sharepoint, I am reading them from the keyVault and then passing them to IJsomNodeContext as follows

            const nodeContext: IJsomNodeContext = {
                siteUrl: siteurl,
                authOptions: {
                    clientId: authOptions.clientId,
                    clientSecret: authOptions.clientSecret,
                    realm: authOptions.realm
                }
            };
            let settings: IJsomNodeSettings = { envCode: "spo" };
            //let authOptions: any = nodeContext.authOptions;
            new JsomNode(settings).init(nodeContext);
When I review the logs, I see the following error message. 
 FailureException: TypeError: Cannot read property 'clientId' of undefinedStack: TypeError: Cannot read property 'clientId' of undefined.  I tried adding the 'let settings' to see if it makes a difference.  

If I add the following line after  before 'let settings:' line, the code does not compile. clientId, clientSecret and realm does not resolve.
            funcContext.log(`ClientId: ${nodeContext.authOptions.clientId}; ClientSecret: ${nodeContext.authOptions.clientSecret}; Realm: ${nodeContext.authOptions.realm}`);

So my guess is I am not initializing the authOptions correctly.  But my confusion is how it works fine from the portal, but does not if i am consuming it from my webpart or postman!!

**Comment by koltyakov** [comment]
Hi @karthikramasubramanian,

For sure, you should pass the creds to the auth context for the code to be able to authenticate.

Please make sure that the underlined variables are populated:

![Image 2021-06-08 16-42-38](https://user-images.githubusercontent.com/7816483/121195869-a97b6880-c878-11eb-8c1a-fa93ee6425d6.png)

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov,

Apologies for not responding to your comment.  
It turned out to be a case sensitive comparison in the conditional assignment of the clientId and clientSecret.  once I updated the code to do the case insensitive comparison, it fixed my issue

Regards
Karthik.

**Comment by koltyakov** [comment]
Thanks for coming back with the update!
