### ISSUE TITLE
timeout issue when connecting to a site in a different tenant.

### ISSUE THREAD

**Issue by karthikramasubramanian** [koltyakov/sp-jsom-node#31]
Hi @koltyakov,

We have a multi-geo, multi-tenant azure enviroment.  I am using the sp-jsom-node in my azure function(s) to connect to sharepoint sites in either of the tenant and get or set regional settings.  The ClientId and ClientSecret are the same for all the tenants.  if I am calling the function to connect to a site in say the Canadian tenant, and if subsequent calls are to sites in the canadian tenant the function does the job fine.  but if the subsequent call is to a site in say US tenant, then the func times out.

Do you have any suggestions on how we can improve the performance or address timeout issue when trying to connect to sites in different tenants?
listing the code i am using to set Regional Settings
```
`const setRegSettings = async (siteurl: string, authOptions: IOnlineAddinCredentials, funcContext: Context, _regSettings: any): Promise<any> => {
    try {
        //let authOptions: any = nodeContext.authOptions;
        funcContext.log(`ClientId: ${authOptions.clientId}; ClientSecret: ${authOptions.clientSecret}; Realm: ${authOptions.realm}`);
        const nodeContext: IJsomNodeContext = {
            siteUrl: siteurl,
            authOptions: <IOnlineAddinCredentials>{
                clientId: authOptions.clientId,
                clientSecret: authOptions.clientSecret,
                realm: authOptions.realm
            }, envCode: "spo"
        };
        new JsomNode().init(nodeContext);
        const timeZoneId = (_regSettings && _regSettings.timeZoneId);
        const time24 = (_regSettings && _regSettings.time24);
        const localeId = (_regSettings && _regSettings.localeId);
        funcContext.log(`SiteUrl: ${siteurl}`);
        const _url = ".sharepoint.com";
        const startIndex = siteurl.indexOf(_url) + _url.length;
        const _partialUrl = siteurl.substring(startIndex);
        funcContext.log(`Tenant Relative Url: ${_partialUrl}`);
        const ctx = new SP.ClientContext(_partialUrl);
        const web = ctx.get_web();
        ctx.load(web, "Title");
        let regionalSettings = web.get_regionalSettings();
        //Find the full list of SharePoint TimeZone IDs here 
        //https://msdn.microsoft.com/library/microsoft.sharepoint.spregionalsettings.timezones.aspx
        ctx.load(regionalSettings);

        await ctx.executeQueryPromise();

        const untypedRS = regionalSettings as any; // `@types/sharepoint` has gaps
        if (timeZoneId) {
            const timeZone = regionalSettings.get_timeZones().getById(timeZoneId); //(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi
            ctx.load(timeZone);
            await ctx.executeQueryPromise();
            funcContext.log(`Setting Timezone to: ${timeZone.get_description()} `);
            untypedRS.set_timeZone(timeZone)
        }
        if (localeId) {
            untypedRS.set_localeId(localeId)
            funcContext.log(`Setting Locale to: ${localeId} `);
        }
        if (time24) {
            funcContext.log(`Setting 24 hr clock to: ${time24} `);
            untypedRS.set_time24(time24); //true/false
        }

        untypedRS.update();
        await ctx.executeQueryPromise();

        return await <ISPWebData>{
            Status: "Success",
            Title: web.get_title(),
            SiteUrl: siteurl,
            RegionalSettings: {
                TimeZone: {
                    Id: untypedRS.get_timeZone().get_id(),
                    Description: untypedRS.get_timeZone().get_description()
                },
                Time24: time24,
                LocaleId: localeId
            }
        };
    }
    catch (err) {
        console.error("Error occurred updating regional settings:");
        console.error(err);
        return await <ISPWebData>{
            Status: "Error",
            Error: err
        };
    };
};`
```
Regards
Karthik

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov,

I did some further investigation and found that the timeout is occurring after the following line of code is executed

        await ctx.executeQueryPromise();

my question i am creating the ctx object and the nodeContext object with a specific site url and then the timeout occurs when we change the url (i.e. with a different geo location url).  so should we say dispose the ctx and\or nodeContext object each time after it finishes executing? 
the first time the function executes it is pretty fast (immaterial of which site we are trying to connect to). but when we change the geo url the timeout happens.  if the second execution is also to a site in the same geo url, the timeout doesnt happen.

Regards
Karthik

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov,
sorry to keep adding to the posts.  I am just passing on whatever info I am finding about the issue.   
I added a few more logging entries and redeployed my azure function.. and found that the call to "await ctx.executeQueryPromise()l "  is throwing the following error:
Unhandled rejection Error: StatusCodeError: 401 - {"error_description":"Exception of type 'Microsoft.IdentityModel.Tokens.AudienceUriValidationFailedException' was thrown."}
Looks like the issue maybe because the ctx object is trying to reuse the bearer Token from the previous instance. I am guessing that based on what I found in the following article - https://blog.velingeorgiev.com/audienceurivalidationfailedexception-sharepoint-token-error

Regards,
Karthik

**Comment by koltyakov** [comment]
Hi @karthikramasubramanian, 

I have not had a chance to work with multi geo instances. It sounds that Bearer received for one geo won't work for another.

In auth library, the token is [cached with a cache key containing clientId and clientSecret](https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/resolvers/OnlineAddinOnly.ts#L22) it ends up reusing tokens per the same creds.

@karthikramasubramanian are you able connecting different GEOs during the first call when nothing is yet cached?

@s-KaiNet, did you have cases with multi geo tenants? Any ideal could the caching be somehow scoped per geo or maybe an adhoc way for custom cache keys?

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov,

Yes it works the 1st time, when nothing is cached, I am able connect to any of the multi geo urls.
So yes a custom cache key or maybe an option to specify that the cache is to be invalidated might work.

Regards

Karthik Ramasubramanian
Sent from my mobile phone

**Comment by karthikramasubramanian** [comment]
Hi @koltyakov,

Thanks for your response, I took a look at the link you had posted.  

> "In auth library, the token is cached with a cache key containing clientId and clientSecret<https://github.com/s-KaiNet/node-sp-auth/blob/master/src/auth/resolvers/OnlineAddinOnly.ts#L22> it ends up reusing tokens per the same creds."

I located the file in my node_modules - node_modules\node-sp-auth\lib\src\auth\resolvers\OnlineAddinOnly.js and modified the  cachekey format as below and tested my azure function.  **This resolves my issue.**

  `      let cacheKey = `${sharepointhostname}-${this._authOptions.clientSecret}@${this._authOptions.clientId}`;`

please let me know if this is fine and we can update the codebase., if so is there anything I should do.

**Comment by koltyakov** [comment]
With multi-geo, are host names different for different GEOs? If so it might be a simple addition to cache key naming pattern.

**Comment by karthikramasubramanian** [comment]
Hi,

Each geo location has a different hostname and therefore, the hostname can be used as a differentiator for the cacekey.

Discover a Multi-Geo tenant configuration | Microsoft Docs<https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-discovery> – this article from Microsoft details multi-geo setup. And how to retrieve the info.

https://....can.sharepoint.com/... For Canada
https://....usa.sharepoint.com/... For USA
https://...aus.sharepoint.com/... For Australia and so on..


Regards,

Karthik Ramasubramanian
Digital Productivity Developer

**Comment by s-KaiNet** [comment]
Hi, 

thank you for all the details you provided here. I will add sharepoint hostname as a dependency for a cache key, hopefully, it will resolve the issue. Please expect the update to be available later today.

**Comment by s-KaiNet** [comment]
I've published `3.0.4` version of `node-sp-auth` with the above fix. Please try it (I guess you should delete `pacakge-lock.json` and `node_modules` and reinstall deps).

**Comment by koltyakov** [comment]
I will also need to bump the depts within the sp-jsom-node, as v2 is still used here. Will keep you posted.

**Comment by koltyakov** [comment]
+ sp-jsom-node@3.2.0

**Comment by karthikramasubramanian** [comment]
Hi Guys,

Thanks for quickly updating the code.. really appreciate it.. I updated my package.json, deleted the node_modules folder and did an npm install.

Checked the package-lock.json and confirmed that the correct versions are updated.  I am getting a build time error when I try to build my azure functions project,
The build error:

***@***.***/request-promise/index.d.ts:27:49 - error TS2694: Namespace 'request' has no exported member 'Response'.

27         transform?(body: any, response: request.Response, resolveWithFullResponse?: boolean): any;

When I did a compare of the package-lock.json, looks like the libraries required by node-sp-auth is missing @types/request-promise and request-promise, among other things.. Let me know if I need to do anything else other than updating the version of sp-jsom-node to 3.2.0?


***@***.***D76CF2.7E286160]



Regards

Karthik Ramasubramanian
Digital Productivity Developer

Norton Rose Fulbright Canada LLP / S.E.N.C.R.L., s.r.l.
45 O'Connor Street, Suite 1500, Ottawa, ON K1P 1A4, Canada

T: +1 613.780.8674  |  M: +1 613.277.2840  |  F: +1 613.230.5459

***@***.******@***.***>
NORTON ROSE FULBRIGHT

**Comment by s-KaiNet** [comment]
In your `tsconfig.json` you can set `skipLibCheck: true` - [source](https://www.typescriptlang.org/tsconfig#skipLibCheck)

**Comment by karthikramasubramanian** [comment]
Hi @s-KaiNet,

I tried your suggestion, the code does compile but it doesn't work.  I am still getting the original error that we are trying to fix. But when i check the node_modules, the changes you have made tot he code have come through... Attaching the screenshot showing that the OnlineAddInOnly.ts has the latest changes. But the code is throwing the 401 error when we try to connect to a site with a different hostname.
![image](https://user-images.githubusercontent.com/43208643/123875909-63bf3680-d932-11eb-9fed-1fb15c19ebdc.png)
when i rollback to the previously used version and manually make the change to the OnlineAddInOnly.ts file in node_modules, the code works fine.

**Comment by s-KaiNet** [comment]
Could you tell the exact version number of `node-sp-auth` which works for you (with your manual modifications)? You can run `npm list node-sp-auth` and it should print the actual version.

**Comment by karthikramasubramanian** [comment]
@s-KaiNet ,
this is the version that works with my manual changes.
![image](https://user-images.githubusercontent.com/43208643/123892699-fec80880-d952-11eb-9fc1-5ac6bb603c7a.png)

**Comment by koltyakov** [comment]
@karthikramasubramanian, 

Could you please try sp-jsom-node@4.0.0, I've manage to adopt sp-request v3.

**Comment by karthikramasubramanian** [comment]
@koltyakov ,

Thanks, that works fine for me.  Thank to both of you for the quick responses and help.  Appreciate it.  
Closing the issue. 
-Karthik
