### ISSUE TITLE
ENOTFOUND when configured siteUrl does not match current site url

### ISSUE THREAD

**Issue by SPWizard01** [koltyakov/sp-jsom-node#5]
scenario:
you have a bunch of web applications(on prem) that you have access to with same user
`{
  "siteUrl": "https://webappone/sites/somesite",
  "strategy": "OnpremiseUserCredentials",
  "username": "user",
  "domain": "dom",
  "password": "encrpwd=="
}`

however if you do
` this.jsomNodeSettngs = await (new JsomNode({ config: this.authConfig })).wizard();
this.jsomCtx = new SP.ClientContext("https://webapptwo/sites/someothersite");`

it will fail because of this:
https://github.com/koltyakov/sp-jsom-node/blob/70618498df13e5d50507c2dae93c145cdeee6f31/src/JsomNode.ts#L246

maybe siteUrl should not be taken into account in this case?

well i could create different configs based on web app, but this would be a nice thing to have.

**Comment by koltyakov** [comment]
Hi @SPWizard01,

Can you try [this approach](https://github.com/koltyakov/sp-jsom-node/blob/master/examples/basic/src/multictxs02.ts) (or [that](https://github.com/koltyakov/sp-jsom-node/blob/master/examples/basic/src/multictxs01.ts)) for multiple contexts? `siteUrl` should be redefined in settings object if you know that different site should be requested while keeping the same user credentials.

Authentication context is a global one (new SP.ClientContext doesn't actually contain any credentials), so if multiple creds/sites the auth context should be switched between them and it should be done sequentially with `new JsomNode(settings).init()` before a physical call to the API.

**Comment by SPWizard01** [comment]
EDIT:

the first approach almost works, ~~however i wanted to use node-sp-auth-config for password encryption, so if i specify~~

~~`new JsomNode({ config: this.authConfig, siteUrl: this.parentUrl }).init();`
it hangs on executeQueryPromise and never returns :) if i specify username password and domain it works fine.~~

~~Is it somehow possible to set the site url but still use password encryption?
or i have to do it myself (encrypt password etc.) ?~~

~~if not i will have to create an env map, just dat bit more of plumbing code :)~~


all i needed is to utilize `let authContext = await new AuthConfig(this.authConfig).getContext();`
along with the first approach :)

**Comment by koltyakov** [comment]
Yep, this is possible. The following sample should help (however, I typed it "blind" without having a chance to verify):

```typescript
import { JsomNode } from 'sp-jsom-node';
import { AuthConfig } from 'node-sp-auth-config';

(async () => {

  const configs = [
    { siteUrl: 'http://site1', configPath: './config/private.env1.json' },
    { siteUrl: 'http://site2', configPath: './config/private.env2.json' }
  ];

  // == Approach A ==
  // Using AuthConfig for getting authOptions
  for (const { siteUrl, configPath } of configs) {
    const { authOptions } = await new AuthConfig({ configPath }).getContext();
    new JsomNode({ siteUrl, authOptions }).init();
    // JSOM actions to specific Environment
  }

  // == Approach B ==
  // Redefining siteUrl within IJsomNodeInitSettings initiation object
  const { siteUrl, configPath } = configs[0];
  new JsomNode({ siteUrl, config: { configPath } }).init();
  // JSOM actions

})()
  .catch(console.warn);
```
