### ISSUE TITLE
sp.search.js and search.clientcontrols.js missing

### ISSUE THREAD

**Issue by SPWizard01** [koltyakov/sp-jsom-node#7]
is there any specific reason this is missing?

my use case is to import search configuration.

**Comment by koltyakov** [comment]
Hi @SPWizard01,

No any particular reason.
Added, but can't test at the moment. Could you please try (`sp-jsom-node@2.1.0`)?
`search` should be explicitly added in the modules list.

```typescript
const jsomSettings: IJsomNodeSettings = {
  modules: [ 'search' ]
};
new JsomNode(jsomSettings).init(authOptions);
```

**Comment by SPWizard01** [comment]
something got messed up :D
(node:26780) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at Function.Object$getType [as getType] (C:\...\node_modules\sp-jsom-node\jsom\spo\msajaxbundle.debug.js:450:38) and its only when i add search as dependency

i will investigate, oh and by the way "search" type is missing, typescript will complain :)

**Comment by koltyakov** [comment]
He he, was over optimistic to expect it works so easy. 
Any investigations are appreciated. Thanks!
I’ll take a deeper look and add tests as well over the weekend.

**Comment by SPWizard01** [comment]
ok, so i got it to work partially, without search.clientcontrols.js
https://github.com/koltyakov/sp-jsom-node/blob/1b243f6fb78cdd60b7d39417f4d7fdc2c79b48a2/src/JsomNode.ts#L162
had to add this:
`registerNamespace('Microsoft.SharePoint.Client.Search');
registerNamespace('Microsoft.Office.Server.Search');`

now if i add:
`registerNamespace('Srch');` <- this is all in search.clientcontrols.js it will the no longer give me maximum stack but rather cannot read property of undefined in here:

https://github.com/koltyakov/sp-jsom-node/blob/1b243f6fb78cdd60b7d39417f4d7fdc2c79b48a2/jsom/spo/search.clientcontrols.debug.js#L9612

so i wonder how its possible because it should be available from:
https://github.com/koltyakov/sp-jsom-node/blob/1b243f6fb78cdd60b7d39417f4d7fdc2c79b48a2/jsom/spo/sp.init.debug.js#L1303

**Comment by SPWizard01** [comment]
and if we add sp.init.js to dependencies it fails here:
https://github.com/koltyakov/sp-jsom-node/blob/1b243f6fb78cdd60b7d39417f4d7fdc2c79b48a2/jsom/spo/sp.init.debug.js#L1401

**Comment by koltyakov** [comment]
I was managed to make it work. Please check just published v2.1.1
However, `search.clientcontrols.js` is still limited (`SP.Utilities.HttpUtility` is faked as an empty object) and I can't recall what was the issue including `sp.init.debug.js`.
Could you also elaborate on your use case of `search.clientcontrols.js` in Node.js app? Hands itching soo much to exclude `search.clientcontrols.js`.

**Comment by SPWizard01** [comment]
i think you are right, this one is only for UI interactions(or so it looks), at least my use case is working without it, bad assumption from my side then :)

**Comment by koltyakov** [comment]
So I likely remove search.clientcontrols.js in the next version. Also considering it's only for UI part.
